language: go

go:
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - 1.8
    - 1.9
    - tip

matrix:
  allow_failures:
    - go: tip
    - go: 1.9

install:
    - source env.sh
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure

script:
    - go test -v -cover ./...
