---
sudo: false

language: go

install:
    - cd $GOPATH/src/github.com/EscherAuth/escher
    - . .envrc

script:
    - go test ./...
    - go test -count=100 -race ./...

os:
    - linux
    - osx

go:
    - "1.x"
    - master

matrix:
    allow_failures:
        - go: master

branches:
    only:
        - master

notifications:
    email:
        - adamluzsi@gmail.com
